name: Publish package & documentation

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Upload build artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          retention-days: 7
          path: |
            dist
            package.json

      - name: Generate documentation
        run: npm run docs

      - name: Upload documentation artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: documentation-artifact
          retention-days: 7
          path: docs

      - name: Generate storybook static files
        run: npm run storybook:build

      - name: Upload storybook artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: storybook-artifact
          retention-days: 7
          path: storybook-static-build

  docs:
    needs: ['build']
    runs-on: ubuntu-latest

    steps:
      - name: Download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation-artifact

      - name: Deploy documentation to GitHub Pages
        if: ${{ success() }}
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages-documentation
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  storybook:
    needs: ['build']
    runs-on: ubuntu-latest

    steps:
      - name: Download storybook artifact
        uses: actions/download-artifact@v3
        with:
          name: storybook-artifact

      - name: Deploy storybook to GitHub Pages
        if: ${{ success() }}
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages-storybook
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: ['build']
    runs-on: ubuntu-latest

    steps:
      - name: Set Node.js to publish
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Download build artifact (dist folder)
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Publish on npmjs registry
        if: ${{ success() }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
