name: Publish package on release tag & publish documentation

on:
  push:
    tags:
      # Tags must follow Semantic Versioning (https://semver.org/)
      - '^v[0-9]+.[0-9]+.[0-9]+$'
      - '^v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+$'
      - '^v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+$'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Upload build artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist
          retention-days: 7

      - name: Generate documentation
        run: npm run docs

      - name: Upload documentation artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: documentation-artifact
          path: docs
          retention-days: 7

  docs:
    needs: ['build']
    runs-on: ubuntu-latest

    steps:
      - name: Download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation-artifact

      - name: Deploy documentation to GitHub Pages
        if: ${{ success() }}
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages-documentation
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: ['build']
    runs-on: ubuntu-latest

    steps:
      - name: Set Node.js to publish
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Download build artifact (dist folder)
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Publish on npmjs registry
        if: ${{ success() }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
